controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motor6_raw_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

motor6_raw_velocity_controller:
  ros__parameters:
    joints:
      - motor6_joint
