controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motor6_raw_position_controller:
      type: forward_command_controller/ForwardCommandController

motor6_raw_position_controller:
  ros__parameters:
    joints:
      - motor6_joint
    interface_name: position
